// docs/princess_design_system/components/feedback/EmptyState.jsx
import React from 'react';

/** Empty state — centered icon + title + message + optional action. Matches app/shared. */

const STYLE_ID = 'pds-empty-styles';
function ensureStyles() {
  if (typeof document === 'undefined' || document.getElementById(STYLE_ID)) return;
  const el = document.createElement('style');
  el.id = STYLE_ID;
  el.textContent = `
  .pds-empty{display:flex;flex-direction:column;align-items:center;justify-content:center;
    padding:64px 24px;text-align:center;gap:8px;font-family:var(--font-sans);}
  .pds-empty__icon{font-size:48px;color:var(--mat-sys-on-surface-variant);opacity:.4;margin-bottom:8px;}
  .pds-empty__title{margin:0;font-family:var(--font-display);font-size:18px;font-weight:600;color:var(--mat-sys-on-surface);}
  .pds-empty__msg{margin:0 0 16px;font-size:14px;color:var(--mat-sys-on-surface-variant);max-width:360px;line-height:1.5;}
  .pds-empty__action{height:40px;padding:0 22px;border-radius:var(--radius-pill);cursor:pointer;
    font-family:var(--font-display);font-weight:500;font-size:.875rem;
    background:transparent;color:var(--mat-sys-primary);border:1px solid var(--mat-sys-outline-variant);}
  .pds-empty__action:hover{background:color-mix(in srgb,var(--mat-sys-primary) 8%,transparent);border-color:var(--mat-sys-primary);}
  `;
  document.head.appendChild(el);
}

export function EmptyState({ icon = 'inbox', title = 'Nothing here', message, actionLabel, onAction, style }) {
  ensureStyles();
  return (
    <div className="pds-empty" style={style}>
      <span className="material-icons pds-empty__icon" aria-hidden="true">{icon}</span>
      <h3 className="pds-empty__title">{title}</h3>
      {message && <p className="pds-empty__msg">{message}</p>}
      {actionLabel && <button className="pds-empty__action" onClick={onAction}>{actionLabel}</button>}
    </div>
  );
}

// src/app/shared/components/empty-state/empty-state.component.ts
import { Component, input, output } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-empty-state',
  imports: [MatIconModule, MatButtonModule],
  template: `
    <div class="empty-state">
      <mat-icon class="empty-state__icon">{{ icon() }}</mat-icon>
      <h3 class="empty-state__title">{{ title() }}</h3>
      <p class="empty-state__message">{{ message() }}</p>
      @if (actionLabel()) {
        <button mat-stroked-button (click)="actionClick.emit()">
          {{ actionLabel() }}
        </button>
      }
    </div>
  `,
  styles: [`
    .empty-state {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 64px 24px;
      text-align: center;
      gap: 8px;

      &__icon {
        font-size: 48px;
        width: 48px;
        height: 48px;
        color: var(--mat-sys-on-surface-variant);
        opacity: 0.4;
        margin-bottom: 8px;
      }

      &__title {
        margin: 0;
        font-size: 18px;
        font-weight: 600;
        color: var(--mat-sys-on-surface);
        font-family: 'Instrument Sans', sans-serif;
      }

      &__message {
        margin: 0 0 16px;
        font-size: 14px;
        color: var(--mat-sys-on-surface-variant);
        max-width: 360px;
        line-height: 1.5;
      }
    }
  `],
})
export class EmptyStateComponent {
  readonly icon = input<string>('inbox');
  readonly title = input<string>('Nothing here');
  readonly message = input<string>('');
  readonly actionLabel = input<string>('');
  readonly actionClick = output<void>();
}
