// docs/princess_design_system/components/ai/AISuggestionCard.jsx
import React from 'react';

/**
 * AI suggestion card — the surface Princess uses to propose actions, pre-fill
 * items, or surface insights from project data. Azure-tinted with the brand
 * "auto_awesome" mark, an explanatory body, and accept/dismiss actions.
 */

const STYLE_ID = 'pds-aisuggestion-styles';
function ensureStyles() {
  if (typeof document === 'undefined' || document.getElementById(STYLE_ID)) return;
  const el = document.createElement('style');
  el.id = STYLE_ID;
  el.textContent = `
  .pds-ai{font-family:var(--font-sans);border-radius:var(--radius-card);padding:16px 18px;
    background:color-mix(in srgb,var(--mat-sys-primary) 6%,var(--mat-sys-surface-container-lowest));
    border:1px solid color-mix(in srgb,var(--mat-sys-primary) 22%,transparent);position:relative;overflow:hidden;}
  .pds-ai::before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--brand-gradient);}
  .pds-ai__head{display:flex;align-items:center;gap:8px;margin-bottom:8px;}
  .pds-ai__spark{width:24px;height:24px;border-radius:6px;display:flex;align-items:center;justify-content:center;
    background:var(--brand-gradient-diagonal);color:#fff;flex:none;}
  .pds-ai__spark .material-icons{font-size:15px;}
  .pds-ai__label{font-family:var(--font-display);font-size:.6875rem;font-weight:600;letter-spacing:.1em;
    text-transform:uppercase;color:var(--mat-sys-primary);}
  .pds-ai__title{margin:0;font-family:var(--font-display);font-size:.95rem;font-weight:600;color:var(--mat-sys-on-surface);}
  .pds-ai__body{margin:4px 0 0;font-size:.875rem;line-height:1.5;color:var(--mat-sys-on-surface-variant);}
  .pds-ai__actions{display:flex;gap:8px;margin-top:14px;}
  .pds-ai__btn{height:34px;padding:0 16px;border-radius:var(--radius-pill);cursor:pointer;
    font-family:var(--font-display);font-weight:500;font-size:.8125rem;border:1px solid transparent;
    display:inline-flex;align-items:center;gap:6px;transition:background var(--duration-base) var(--ease-standard);}
  .pds-ai__btn .material-icons{font-size:16px;}
  .pds-ai__btn--accept{background:var(--mat-sys-primary);color:var(--mat-sys-on-primary);}
  .pds-ai__btn--accept:hover{background:color-mix(in srgb,var(--mat-sys-primary) 90%,#000);}
  .pds-ai__btn--dismiss{background:transparent;color:var(--mat-sys-on-surface-variant);}
  .pds-ai__btn--dismiss:hover{background:color-mix(in srgb,var(--mat-sys-on-surface) 7%,transparent);}
  `;
  document.head.appendChild(el);
}

export function AISuggestionCard({
  title,
  children,
  label = 'AI Suggestion',
  acceptLabel = 'Apply',
  dismissLabel = 'Dismiss',
  onAccept,
  onDismiss,
  style,
}) {
  ensureStyles();
  return (
    <div className="pds-ai" style={style}>
      <div className="pds-ai__head">
        <span className="pds-ai__spark"><span className="material-icons" aria-hidden="true">auto_awesome</span></span>
        <span className="pds-ai__label">{label}</span>
      </div>
      {title && <h4 className="pds-ai__title">{title}</h4>}
      {children && <p className="pds-ai__body">{children}</p>}
      {(onAccept || onDismiss) && (
        <div className="pds-ai__actions">
          {onAccept && <button className="pds-ai__btn pds-ai__btn--accept" onClick={onAccept}>
            <span className="material-icons" aria-hidden="true">check</span>{acceptLabel}</button>}
          {onDismiss && <button className="pds-ai__btn pds-ai__btn--dismiss" onClick={onDismiss}>{dismissLabel}</button>}
        </div>
      )}
    </div>
  );
}

// src/app/shared/components/ai-suggestion-card/ai-suggestion-card.component.ts
import { Component, input, output } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-ai-suggestion-card',
  imports: [MatIconModule, MatButtonModule],
  template: `
    <div class="ai-card">
      <div class="ai-card__header">
        <span class="ai-card__spark-tile">
          <mat-icon class="ai-card__spark-icon">auto_awesome</mat-icon>
        </span>
        <span class="ai-card__eyebrow">{{ eyebrow() }}</span>
      </div>

      <p class="ai-card__title">{{ title() }}</p>
      <div class="ai-card__body"><ng-content /></div>

      <div class="ai-card__actions">
        <button mat-flat-button class="ai-card__accept" (click)="accepted.emit()">
          <mat-icon>check</mat-icon>
          {{ acceptLabel() }}
        </button>
        <button mat-button class="ai-card__dismiss" (click)="dismissed.emit()">
          {{ dismissLabel() }}
        </button>
      </div>
    </div>
  `,
  styles: `
    .ai-card {
      position: relative;
      border-radius: var(--radius-card);
      padding: 16px 18px;
      background: color-mix(in srgb, var(--mat-sys-primary) 6%, var(--mat-sys-surface-container-lowest));
      border: 1px solid color-mix(in srgb, var(--mat-sys-primary) 22%, transparent);
      overflow: hidden;

      /* 3px left gradient accent bar */
      &::before {
        content: '';
        position: absolute;
        left: 0;
        top: 0;
        bottom: 0;
        width: 3px;
        background: var(--brand-gradient);
      }

      &__header {
        display: flex;
        align-items: center;
        gap: 10px;
        margin-bottom: 10px;
      }

      &__spark-tile {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 24px;
        height: 24px;
        border-radius: 6px;
        background: var(--brand-gradient-diagonal);
        flex-shrink: 0;
      }

      &__spark-icon {
        font-size: 15px;
        width: 15px;
        height: 15px;
        color: #fff;
      }

      &__eyebrow {
        font-family: var(--font-display);
        font-size: 0.6875rem;
        font-weight: 600;
        letter-spacing: 0.1em;
        text-transform: uppercase;
        color: var(--mat-sys-primary);
      }

      &__title {
        margin: 0 0 6px;
        font-family: var(--font-display);
        font-size: 0.95rem;
        font-weight: 600;
        color: var(--mat-sys-on-surface);
      }

      &__body {
        font-family: var(--font-sans);
        font-size: 0.875rem;
        line-height: 1.5;
        color: var(--mat-sys-on-surface-variant);
      }

      &__actions {
        display: flex;
        align-items: center;
        gap: 8px;
        margin-top: 14px;
      }

      &__accept.mat-mdc-button {
        height: 34px;
        border-radius: var(--radius-pill);
        font-family: var(--font-display);
        font-size: 0.8125rem;
      }

      &__dismiss.mat-mdc-button {
        height: 34px;
        border-radius: var(--radius-pill);
        font-family: var(--font-display);
        font-size: 0.8125rem;
        color: var(--mat-sys-on-surface-variant);
      }
    }
  `,
})
export class AISuggestionCardComponent {
  readonly title = input.required<string>();
  readonly eyebrow = input<string>('AI Suggestion');
  readonly acceptLabel = input<string>('Apply');
  readonly dismissLabel = input<string>('Dismiss');

  readonly accepted = output<void>();
  readonly dismissed = output<void>();
}
